Game of Life Memory Leak Fix + Other Changes
MoonModules/WLED pull request #133
Opened 2024-05-24 18:19 UTC by Brandon502

Fixed memory leak using new. Removed gameoflife struct and reverted back to using pointers to segenv.data (similar to starLeds version). 

Added Blur slider. Blurs dead cells slowly to bgColor depending on slider instead of immediately dying. Doesn't effect game logic.

Removed confusing pauseFrames, uses .step to pause now.

Keeps track of last palette used and immediately recolors cells if new palette/color selected. Can be improved.

Changes gameSpeed slider to be more consistent. Speed = updates/second now in increments of 4.

2024-05-24 18:23 UTC, Brandon502 commented
Please look over palette change code and game speed. 
I couldn't figure out a way to store the actual previous palette used, so it cheats by just using the first color of the palette. This works most of the time. Only doesn't switch immediately if two palettes share same 0 index color (rainbow/rainbow stripe).
Game update speed is capped to 64 updates/second which may be too fast depending on setup. Not sure if this can cause issues so may need adjusting.

2024-06-03 11:02 UTC, softhack007 commented
Hi, thanks for this update.
I'll look into the details like game speed in the next days, and then we can merge it into the code for the new release of WledMM (it's still the same "upcoming" release) 

> I couldn't figure out a way to store the actual previous palette used, so it cheats by just using the first color of the palette

You could use `uint8_t currentPal = SEGMENT.palette;` to get the current palette ID.
Downside: sometimes a palette is dynamically adjusted, while the ID stays the same. For example: during effect blending, or when using one of the audioreactive palettes. So this would also not make the code 100% bullet proof.

But your "cheat" is OK for me, too. I doesn't need to be perfect.

2024-06-04 01:05 UTC, Brandon502 commented
`uint8_t currentPal = SEGMENT.palette;`

Some how overlooked this. Didn't think about palettes that change overtime, keeping the first color would work better for those. Each method seems to have a slight drawback, implementing both would be overkill. I'll have to test out those special palettes. 

I have a few more changes I've made in StarLeds that I need to convert to WLED and push. Finally figured out a way to make blending look better when a game starts repeating.

2024-06-04 20:29 UTC, Brandon502 commented
I'll post videos when I get a chance later. Code is a bit more complicated, especially the new redraw loop. Added new blend option when blur slider >220. There is an unintended effect when you have two segments and overlay off. Looks really good on high game speeds, but breaks (flashes) on lower ones. Tried a few ways to get it working on lower speeds but no luck. 

Default parameters don't seem to be working. May just be using progmem incorrectly. 

futureCells is technically not needed to be stored in memory. It is only needed when game updates occur.

2024-06-05 01:44 UTC, Brandon502 commented
Short video showing the new options. 

- Top left: Blur >220. The background keeps a faded color of the last alive cell on that led. Kind of a history/turf war of the alive colors. 
- Top right: High blur value with multiple palette changes to show instant switching and blur fading as the game ends. 
- Bottom left: Unintended effect when you turn off overlay when you have another effect in the background. Alive cells take the background color and you can apply a different blur color. Video shows white then switching to Atlantica. 
- Bottom right: Side effect when game speed is too low, tons of flashing since there are effects stacked. May be able to figure out how to prevent it so there would be a second overlay type without a toggle.


https://github.com/MoonModules/WLED/assets/105077712/b96e22b7-d23b-4d92-b382-e5b096a5524f

2024-06-05 16:43 UTC, Brandon502 commented
Stress tested on a 64x32 matrix with 4 pins. Showing 30 FPS with max game speed. 40+ when updating is set to 20/sec.


https://github.com/MoonModules/WLED/assets/105077712/509842ee-bd31-4ba5-af87-ae236eb5d219

2024-06-19 17:29 UTC, softhack007 requested changes
Hi, thanks for the update.
i've tested your new code quickly, and it works for me. 

Below some recommendations that could slightly improve speed.

2024-06-19 17:29 UTC, softhack007 commented on wled00/FX.cpp
> +    CRGB color = SEGMENT.getPixelColorXY(x,y);
style: this variable "shadows" the global color defined on line 5194. Maybe better to use a "unique" name.

2024-06-19 17:29 UTC, softhack007 commented on wled00/FX.cpp
> +      else if (!overlayBG) SEGMENT.setPixelColorXY(x,y, allColors ? RGBW32(bgColor.r, bgColor.g, bgColor.b, 0) : bgColor); // set background color if not overlaying
maybe i missed something - it seems like "then" and "else" sides of the `?` operator are the same? 
because CRGB does not have a "white" channnel.

2024-06-19 17:29 UTC, softhack007 commented on wled00/FX.cpp
> +    else if (blurDead && !alive) SEGMENT.setPixelColorXY(x,y, blend(color, bgColor, blur));                                     // Blur dead cells (paused)
optimization: you could use `color_blend()` instead of `blend()`

https://github.com/MoonModules/WLED/blob/fc173b3bc00694e59b653ca230133052b5476c05/wled00/fcn_declare.h#L53

The WLED function color_blend() is slightly faster because it can handle all color components in one "shot".
You only have to use `uint32_t` instead of `CRGB` for colors. `uint32_t` (aka RGBW32) is the "WLED native" format for colors. 

In case you need to convert from CRGB to RGBW32, its necessary to mask off the highest byte after conversion: `uint32_t wled_color = uint32_t(fastled_color) & 0x00FFFFFF`.

2024-06-19 17:29 UTC, softhack007 commented on wled00/FX.cpp
> +      if (!overlayBG) SEGMENT.setPixelColorXY(x,y, blend(SEGMENT.getPixelColorXY(x,y), bgColor, bgBlendMode ? bgBlur : blur));
optimization: try to use color_blend() instead of blend()

2024-06-19 17:29 UTC, softhack007 commented on wled00/FX.cpp
> +    else if (overlayBG & alive) SEGMENT.setPixelColorXY(x,y, allColors ? RGBW32(color.r, color.g, color.b, 0) : color);         // Redraw alive cells for overlayBG
same question - is there a difference between `RGBW32(color.r, color.g, color.b, 0)` and `color`?

2024-06-19 17:50 UTC, Brandon502 commented on wled00/FX.cpp
> +      else if (!overlayBG) SEGMENT.setPixelColorXY(x,y, allColors ? RGBW32(bgColor.r, bgColor.g, bgColor.b, 0) : bgColor); // set background color if not overlaying
I agree they're the same. This was code I kept from the original version since I didn't know if it was required for RGBW setups that I couldn't test on.

2024-06-19 17:52 UTC, Brandon502 commented on wled00/FX.cpp
> +    else if (blurDead && !alive) SEGMENT.setPixelColorXY(x,y, blend(color, bgColor, blur));                                     // Blur dead cells (paused)
I'll look into using uint32_t instead of CRGB along with color_blend()

2024-06-19 19:19 UTC, Brandon502 commented
Is this a known issue regarding overlays "breaking"?

Normal overlay:

https://github.com/MoonModules/WLED/assets/105077712/b2abfa95-27de-4382-9f70-6a8bed544e0d

Glitched overlay:

https://github.com/MoonModules/WLED/assets/105077712/89591222-101b-42e8-b9f6-2e44133c975d

Seems like the segments start sharing colors instead of keeping them separate. It allows for some neat effects. Just makes debugging annoying when I don't want it to happen.


https://github.com/MoonModules/WLED/assets/105077712/b258c860-a12d-4192-85b5-1b9a2720d335

2024-06-19 19:42 UTC, softhack007 commented on wled00/FX.cpp
> +    else if (overlayBG & alive) SEGMENT.setPixelColorXY(x,y, allColors ? RGBW32(color.r, color.g, color.b, 0) : color);         // Redraw alive cells for overlayBG
minor (style): 'overlayBG' is used in a bitwise '&' operation. Might be better to use '&&'

2024-06-19 19:49 UTC, softhack007 commented on wled00/FX.cpp
> +      if (!cellValue && !overlayBG && !bgBlendMode) SEGMENT.setPixelColorXY(x,y, blend(SEGMENT.getPixelColorXY(x,y), bgColor, bgBlendMode ? bgBlur : blur));
this line can be simplified a bit, because `bgBlendMode` must be false due to `if (!cellValue && !overlayBG && !bgBlendMode)`

2024-06-19 19:56 UTC, softhack007 commented
> Is this a known issue regarding overlays "breaking"?

Normally not - only two exceptions that I know about
* "Use global LED buffer" is enabled, making all pixels shared (plus known bug https://github.com/MoonModules/WLED/issues/58)
* effects run with 1D->2D mapping (pinwheel, bar, etc.) In this case the segment buffer cannot be used.

2024-06-19 22:19 UTC, softhack007 commented on wled00/FX.cpp
> +      else if (!overlayBG) SEGMENT.setPixelColorXY(x,y, allColors ? RGBW32(bgColor.r, bgColor.g, bgColor.b, 0) : bgColor); // set background color if not overlaying
Good point about RGBW. I dow 't have any rgbw panels either, however I'll do some testing by changing my "virtual" 52x52 to sk6812 and checking preview.

2024-06-19 23:09 UTC, Brandon502 commented
@softhack007 I think I made all your recommended changes. Although I am not sure when to use `uint32_t wled_color = uint32_t(fastled_color) & 0x00FFFFFF` conversion. Currently just set all CRGB to uint32. Everything seems to work, using color_blend didn't have a noticeable affect on FPS on my end, ~+1 FPS.

2024-06-20 05:15 UTC, Brandon502 commented
Finally got alive cells to spawn in randomly on game start working on everything, but overlayBG. Had a small flicker on start so decided to remove it. Looks a lot better with transition between games. The redraw loop is even more complicated now unfortunately.

2024-06-20 14:18 UTC, softhack007 approved these changes
Thanks, looks good 👍 

Just tell once you're happy with the code, and i'll merge it into mdev.

2024-06-20 16:04 UTC, Brandon502 commented
> Thanks, looks good 👍
> 
> Just tell once you're happy with the code, and i'll merge it into mdev.

Sounds good, I'll play around with it some more for a day or two to make sure everything is working normally and no bugs pop up. I'll let you know soon.

2024-06-22 21:40 UTC, Brandon502 commented
@softhack007 Haven't run into any bugs on my setup so far. Feel free to merge whenever.

2024-06-22 22:17 UTC, merged