Art-Net Improvements v2
MoonModules/WLED pull request #179
Opened 2024-11-07 18:39 UTC by troyhacks

Fully implemented new Art-Net codebase.

Improvements:

* AsyncUDP instead of WiFiUDP so it's much faster
* Support for professional Art-Net gear with many outputs
* Color-order remapping
* ESP32-P4 assembly optimization for brightness calc, a bit faster
* Full GUI support for all settings
* GUI guidance for setup:

![chrome_lfXtWhKwfN](https://github.com/user-attachments/assets/b683b177-a872-454f-b6ae-e59c46bfaf14)

2024-11-07 20:40 UTC, softhack007 commented on wled00/bus_manager.cpp
> +uint32_t IRAM_ATTR BusNetwork::getPixelColor(uint16_t pix) const {
🤔 looks like all 8266 builds fail with `.pio/build/esp8266_2MB_S/firmware.elf section `.text1' will not fit in region `iram1_0_seg` ...

Try to change `IRAM_ATTR` into `IRAM_ATTR_YN` - this is a trick that does _not_ put a function into IRAM on 8266, but it will still be IRAM on esp32.

2024-11-07 20:41 UTC, softhack007 commented on wled00/udp.cpp
> +uint8_t IRAM_ATTR realtimeBroadcast(uint8_t type, IPAddress client, uint16_t length, uint8_t *buffer, uint8_t bri, bool isRGBW, uint8_t outputs, uint16_t leds_per_output, uint8_t fps_limit)  {
same here ... this could be IRAM_ATTR_YN

2024-11-07 22:09 UTC, troyhacks commented
GUI demo:

https://github.com/user-attachments/assets/2e215914-3f8c-4335-83b2-75e84a8219f0

2024-11-07 23:09 UTC, troyhacks commented
@softhack007 Checks all green - your fix was what it needed, thanks!

2024-11-08 13:48 UTC, softhack007 commented
@troyhacks would it make sense to add proxy mode support fixes from
* https://github.com/Aircoookie/WLED/pull/3863

Just if that's _not_ a corner case which makes the code complicated or unstable ....

2024-11-08 14:10 UTC, troyhacks commented
> @troyhacks would it make sense to add proxy mode support fixes from
> 
> * [Use correct start index for Art-Net in proxy mode Aircoookie/WLED#3863](https://github.com/Aircoookie/WLED/pull/3863)
> 
> Just if that's _not_ a corner case which makes the code complicated or unstable ....

That's unrelated to my code. I'm doing Art-Net output here, not input. 

I guess you could consider it related if I was sending Art-Net data to another WLED board with DMX and expecting it to proxy to wired DMX, but that's an edge case and should be considered separately. (I think that other PR is fine, but @netmindz might have opinions.)

2024-11-08 22:50 UTC, softhack007 commented on wled00/bus_manager.cpp
> +  // _data = nullptr;
is there a special reason that these two are commented out?
The "BusNetwork" gets deleted and re-initailized each time that the LEDs setting page is saved.

So without the "free(_data)" memory is leaked.
Or maybe the _data array is still needed/used ?

2024-11-08 23:26 UTC, softhack007 commented on wled00/bus_manager.h
> +    uint8_t getColorOrder() const {
(minor) override could be added.
```c++
uint8_t getColorOrder() const override {
```

2024-11-08 23:26 UTC, softhack007 commented on wled00/bus_manager.h
> +    uint8_t getPins(uint8_t* pinArray) const;
(minor) while fixing blanks, we could also add 'override'
```C++
    uint8_t getPins(uint8_t* pinArray) const override;
```

2024-11-08 23:33 UTC, softhack007 commented on wled00/bus_manager.cpp
> +  _artnet_fps_limit = bc.artnet_fps_limit;
this will later be used in `1000/fps`, so better to make sure the value is never zero.

```c++
  _artnet_fps_limit = max(uint8_t(1), bc.artnet_fps_limit);  // robustness: avoid division by zero
```

2024-11-08 23:37 UTC, softhack007 commented on wled00/udp.cpp
> +      static uint_fast16_t artnetlimiter = millis()+(1000/fps_limit);
`artnetlimiter` should be "unsigned long" because the return value of 'millis()' is unsigned long

2024-11-08 23:43 UTC, softhack007 commented on wled00/udp.cpp
> +      while (artnetlimiter > micros()) {
🤔 you initialized artnetlimiter with millis(), while the loop (and line 1015, too) uses `micros()`. 
Looks like the initial value is wrong?

2024-11-08 23:57 UTC, softhack007 commented on wled00/udp.cpp
> +      uint_fast16_t timer = micros();
should be `unsigned long timer = micros();`

2024-11-08 23:58 UTC, softhack007 commented on wled00/udp.cpp
> +      artnetlimiter = micros()+(1000000/fps_limit)-(micros()-timer);
I think this line could be simplified ?

```text
The expression micros()+(1000000/fps_limit)-(micros()-timer) 
can be further simplified by expanding the parentheses and combining the terms:
     micros() + (1000000/fps_limit) - micros() + timer
micros() is both added and subtracted, so the term is equal to
    (1000000/fps_limit) + timer;
```

(yeah, I was tired so I asked the AI to simplify ;-) )

```c++
     artnetlimiter = timer + (1000000/fps_limit);
```

2024-11-09 22:39 UTC, troyhacks commented on wled00/bus_manager.cpp
> +  // _data = nullptr;
I feel like I commented these out to prevent a crash that was happening when removing a network bus - but I'll test it again and see what's actually going on.

2024-11-10 12:25 UTC, troyhacks commented on wled00/udp.cpp
> +      while (artnetlimiter > micros()) {
Yea, 100%. I use millis() initially, but moved to micros() later for more accuracy.

2024-11-10 12:26 UTC, troyhacks commented on wled00/udp.cpp
> +      static uint_fast16_t artnetlimiter = millis()+(1000/fps_limit);
Also needed adjusted for micros() 

micros()+(1000000/fps_limit)

2024-11-10 13:56 UTC, troyhacks commented on wled00/udp.cpp
> +      artnetlimiter = micros()+(1000000/fps_limit)-(micros()-timer);
I've looked at this 5 times and gone back and forth on if it's correct or not. 

The AI is correct in the expansion and simplification... so that means I was wrong in the calculation? Or was I? 🤣

Originally I calculated the microseconds for when to start the next frame as: 

`artnetlimiter = micros() + (1000000/fps_limit);` 

...but I figured there's "natural delay" in calculating and sending packets, so let's remove `timer` from that so we can be closer to the real FPS we want:

`artnetlimiter = micros()+(1000000/fps_limit)-(micros()-timer);`

Now "FrankAI" suggests:

`artnetlimiter = timer + (1000000/fps_limit);` 

It's correct because `timer` holds the value of micros() from the start of the Art-Net frame output, so this is essentially precalculated.

Broke my brain. Good catch, @softhack007 👍🏻

2024-11-10 18:37 UTC, troyhacks commented on wled00/bus_manager.cpp
> +  // _data = nullptr;
Works fine with it re-added. Likely something dumb I was doing with Art-Net previously. 🤣

2024-11-15 13:42 UTC, troyhacks commented
@softhack007 All changes you flagged in the review have been implemented, including the free().

Should be good to merge.

2024-11-16 20:44 UTC, softhack007 commented on wled00/data/settings_leds.htm
> +						if (outputs > 1) {
I think these JS variables should be declared with `var` or `const` or `let`.
@netmindz I'm not a JS expert ... what do you think?

2024-11-16 20:45 UTC, softhack007 commented on wled00/data/settings_leds.htm
> +
additional blank line could be removed

2024-11-16 21:01 UTC, softhack007 commented on wled00/udp.cpp
> +static uint_fast16_t framenumber = 0;
looks like this is never used?

2024-11-16 21:12 UTC, netmindz commented on wled00/data/settings_leds.htm
> +						if (outputs > 1) {
My JavaScript experience is very minimal sorry, but var would be what I would use (rightly or wrongly)

2024-11-16 21:12 UTC, netmindz commented
Looks good to me

2024-11-16 21:13 UTC, netmindz approved these changes

2024-11-16 21:25 UTC, softhack007 commented
@troyhacks some problem with the UI - i cannot save the LED settings page

![image](https://github.com/user-attachments/assets/1d702bf4-4b71-4b60-8c4e-13e543d06736)

i'll see what can be done ...

2024-11-16 22:23 UTC, softhack007 requested changes

2024-11-16 22:23 UTC, softhack007 commented on wled00/data/settings_leds.htm
> +					gId("dig"+n+"F").style.display = (t == 82 || t == 83) ? "inline":"none";  // show Art-Net FPS limiter
@troyhacks I had to add the follwing lines, otherwise saving with non-artnet outputs (HUB75 or ws2812) was not possible.

```js
					d.getElementsByName("AO"+n)[0].min = (t == 82 || t == 83) ? 1 : -1;  // make sure these fields do not block saving when hidden
					d.getElementsByName("AL"+n)[0].min = (t == 82 || t == 83) ? 1 : -1;
					d.getElementsByName("AF"+n)[0].min = (t == 82 || t == 83) ? 1 : -1;
```

please check this solution works for you, too.

2024-11-16 22:31 UTC, softhack007 commented on wled00/data/settings_leds.htm
> +					gId("dig"+n+"O").style.display = (t == 82 || t == 83) ? "inline":"none";  // show Art-Net output number
I think you missed to hide the "W" div

![image](https://github.com/user-attachments/assets/bfe1f29d-a21b-4b92-b353-408950b4e9e2)

2024-11-17 12:29 UTC, troyhacks commented on wled00/data/settings_leds.htm
> +					gId("dig"+n+"O").style.display = (t == 82 || t == 83) ? "inline":"none";  // show Art-Net output number
Ahh yes. Totally did. Will fix.

2024-11-18 08:52 UTC, softhack007 approved these changes

2024-11-18 12:46 UTC, softhack007 commented
Thanks 👍 I'm merging now.

2024-11-18 12:47 UTC, merged