Implement dmx input with rdm support
MoonModules/WLED pull request #64
Opened 2023-08-14 12:52 UTC by arneboe

Currently I am maintaining an old fork of WLED that supports dmx input with rdm using the esp_dmx library.
I would like to get rid of that fork and instead use MoonModules with as little changes as possible.
My usecase is having dmx input with rdm and dmx output work at the same time (using two max495 on port 1 and 2).

I worked through @netmindz dmx input and dmx output branches trying to get them to work and adapt them to my usecase. 

Juggling those branches was kinda challenging for me because they are tracking and old commit of WLED and an old version of esp_dmx and dmx input and output where kinda entangled. Thus I decided to clean it up a bit.
That kinda got out of hand and here we are. (I hope you don't mind :heart: )

The goals for this PR are:
- [x] Have completely different code paths for dmx input and dmx output
- [x] Use esp_dmx for dmx input on esp32 
- [x] Support setting the dmx input address via rdm
- [x] Support setting the dmx input personality via rdm
- [x] Support dmx input rdm identify requests
- [x] Some cleanup and correct error handling

**edit:** From my point of view this PR is ready to merge. It is working as intended in my test cases.

2023-08-14 18:49 UTC, netmindz commented
Sounds like great goals. Let me know if there are any specific questions you have while trying to complete this PR

2023-08-17 13:59 UTC, arneboe commented
I am having trouble with a crash that happens when dmx is received while the wifi hotspot is being activated.
I am getting the "Cache disabled but cached memory region accessed" panic. 
My guess is, that activating wifi disables the cache.
But the dmx driver has been placed in IRAM so this shouldn't happen? 

When I wait until wifi has been activated before connecting dmx, it works fine. 
But this is not a feasible solution because devices are connected to the dmx bus before they are turned on :D

2023-08-17 14:44 UTC, arneboe commented
Calling `dmx_receive` with zero timeout does never receive any data.
I am unsure if this is a bug or intended behavior.
I created an issue https://github.com/someweisguy/esp_dmx/issues/87 on esp_dmx to resolve that question.

If this is intended behavior, I will probably have to move the dmx_receive code over into its own task. Do you see any problems with that? And should I pin it to core 0 or 1? Afaik all the arduino stuff runs on core 1, so maybe pinning it to core 0 is a good idea?

2023-08-18 14:42 UTC, arneboe commented
> Sounds like great goals. Let me know if there are any specific questions you have while trying to complete this PR

I have a specific question :D
If the user changes the dmx start address using rdm, how can I store it permanently? Probably I have to use the same code path that the web interface is using. But i cannot figure out how the web interface saves data.

2023-08-22 21:54 UTC, softhack007 commented
> [arneboe](https://github.com/arneboe) [force-pushed](https://github.com/MoonModules/WLED/compare/fa4ad138e7f6161982d30c2d2ecb43daf73f7266..5070b1da4a0f617ae7a79e12290430b1bf21b5e2) the dmx_input branch

@arneboe please try to avoid force-pushing. It may cause lots of weird behaviour on github later.

2023-08-23 11:20 UTC, arneboe commented
> > [arneboe](https://github.com/arneboe) [force-pushed](https://github.com/MoonModules/WLED/compare/fa4ad138e7f6161982d30c2d2ecb43daf73f7266..5070b1da4a0f617ae7a79e12290430b1bf21b5e2) the dmx_input branch
> 
> @arneboe please try to avoid force-pushing. It may cause lots of weird behaviour on github later.
> 
> If you need to copy single commits from one branch to another, it's better to use cherry-picking. It even works between different repositories.
> 
> https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/cherry-picking-a-commit-in-github-desktop

I am force pushing for several reasons:
- rebasing this branch on top of changes that have happened in mdev since I forked.
- Modifying existing commits because I forgot to push things that belong to that commit.
Both of those shouldn't cause problems when merging later. Rebasing makes the merge easier and modifying my own commits shouldn't matter because they do not exist on the main branch.

I agree, that copying single commits from somewhere should be done by cherry picking. But that is not what I am doing here.

2023-08-23 11:26 UTC, arneboe commented
The dmx input side is more or less done and I would appreciate some reviews :-)
It is tested and working using a Botex RDM/DMX tester. But that is just one test. Maybe someone else could test it aswell. 

However, it relies on changes that I made to esp_dmx that are stil under review. Thus for now this PR is tracking my fork of esp_dmx until the following PRs are merged:
https://github.com/someweisguy/esp_dmx/pull/90
https://github.com/someweisguy/esp_dmx/pull/92
https://github.com/someweisguy/esp_dmx/pull/93

2023-08-23 13:48 UTC, arneboe commented
For readability reasons I would like to implement dmx output in a different PR.
Otherwise this gets really hard to review.
Also, I am not sure if there is any benefit in using esp_dmx for the dmx output if the sparkfun lib works just fine? What do you think? @netmindz @softhack007

2023-08-25 19:01 UTC, arneboe commented
I had to put the dmx receiver into its own task on core 0.
Otherwise it was not able to respond to rdm requests in time (there is only a few micros to respond due to how rdm works).
I am not sure if this breaks anything else?.It works for me :D

2023-08-27 09:23 UTC, netmindz commented
Sorry for not replying, having some health issues. Should hopefully be able to look at soon

2023-09-03 13:57 UTC, arneboe commented
> Sorry for not replying, having some health issues. Should hopefully be able to look at soon

No need to apoligize :) Take your time!

2023-09-24 11:31 UTC, arneboe commented
All required changes have been merged into esp_dmx upstream. Thus I removed my custom branch of esp_dmx. 
I rebased this branch on top of mdev again to keep it easy to merge.

2023-09-30 10:42 UTC, netmindz requested changes

2023-09-30 10:42 UTC, netmindz commented on platformio.ini
> +  https://github.com/someweisguy/esp_dmx.git#release/v3.1  ;; for DMX_INPUT
Please link to a tag rather than branch so we get predictable builds, If no such suitable tag exists, please use known good commit

2023-09-30 10:42 UTC, netmindz commented on tools/cdata.js
> -#ifdef WLED_ENABLE_DMX
While I understand the reason to rename now we have support for input as well as output, this would be a breaking change and a MR about input doesn't really feel the right place to redefine how to enable output

2023-09-30 10:42 UTC, netmindz commented on wled00/dmx_input.cpp
> +  config.dmx_start_address = DMXAddress; // TODO split between input and output address
Surely output has no start address, only addresses for the fixtures?

2023-09-30 10:42 UTC, netmindz commented on wled00/dmx_input.cpp
> +  if (rxPin > 0 && enPin > 0 && txPin > 0)
Enable is actually optional with the newer RS485 adapters

2023-09-30 10:42 UTC, netmindz commented on wled00/dmx_input.cpp
> +    {
why the flip in code style to { on new line?

2023-09-30 10:42 UTC, netmindz commented on wled00/dmx_input.cpp
> +  // TODO not sure if this is the correct way?
Would be better to flip to the solid effect with maybe a specific colour?

2023-09-30 10:42 UTC, netmindz commented on wled00/dmx_input.h
> +  uint8_t inputPortNum = 255;
why initialize as 255?

2023-09-30 10:42 UTC, netmindz commented on wled00/dmx_input.h
> +  byte dmxdata[DMX_PACKET_SIZE]; //TODO add locking somehow? maybe double buffer?
todo still outstanding?

2023-09-30 10:42 UTC, netmindz commented on wled00/dmx_output.cpp
> + * Support for DMX input and output via serial (e.g. MAX485).
Surely your change means it's back to output only?

2023-09-30 10:47 UTC, netmindz commented
Sorry it's taken so long to get back to you @arneboe

Overall I would say great contribution, you have cleaned up my initial implementation quite a bit, just a few minor issues to address

2023-09-30 20:55 UTC, arneboe commented
> Sorry it's taken so long to get back to you @arneboe
> 
> Overall I would say great contribution, you have cleaned up my initial implementation quite a bit, just a few minor issues to address

Thanks for the review. I ll fix everything within the next days :)

2023-10-22 18:27 UTC, arneboe commented on wled00/dmx_input.cpp
> +  if (rxPin > 0 && enPin > 0 && txPin > 0)
The esp_dmx library requires an en pin. The user can set any unused gpio if their rs485 adapter does not require an en pin. But some pin has to be set.

2023-10-22 18:28 UTC, arneboe commented on wled00/dmx_input.cpp
> +    {
vscode auto-formatter. I'all revert that.

2023-10-22 18:32 UTC, netmindz commented on wled00/dmx_input.cpp
> +  if (rxPin > 0 && enPin > 0 && txPin > 0)
Thought I was passing 0 or -1 before

2023-10-22 18:32 UTC, netmindz commented on wled00/dmx_input.cpp
> +  if (rxPin > 0 && enPin > 0 && txPin > 0)
(when not required)

2023-10-22 18:33 UTC, arneboe commented on wled00/dmx_input.h
> +  uint8_t inputPortNum = 255;
Just some invalid value.

2023-10-22 18:43 UTC, arneboe commented on wled00/dmx_input.cpp
> +  // TODO not sure if this is the correct way?
I decided against that because effects might not be available depending on `DmxMode`. Solid is only available if one of the effect modes is selected. For all other modes I would have to enable the leds manually anyway.

2023-10-22 18:44 UTC, arneboe commented on wled00/dmx_input.h
> +  byte dmxdata[DMX_PACKET_SIZE]; //TODO add locking somehow? maybe double buffer?
Nope. There is a mutex `dmxDataLock` to guard against that. Just forgot to remove the comment,

2023-10-22 18:52 UTC, arneboe commented on tools/cdata.js
> -#ifdef WLED_ENABLE_DMX
Reverted

2023-10-22 19:08 UTC, arneboe commented on wled00/dmx_input.cpp
> +  if (rxPin > 0 && enPin > 0 && txPin > 0)
I poked around a bit in esp_dmx and it looks like the pin has to fulfill `GPIO_IS_VALID_OUTPUT_GPIO`. Otherwise esp_dmx will fail to initialize.

2023-10-22 19:12 UTC, netmindz commented on wled00/dmx_input.cpp
> +  // TODO not sure if this is the correct way?
Fair enough

2023-12-13 21:18 UTC, netmindz commented
Sorry, I've not tested this yet @arneboe I've not got a suitable test setup at the moment. I have shared links to this on Discord and asked others to help test but I've not heard back. Can you try and get others to test too? You will also need to resolve the merge conflicts before I can merge

2023-12-13 21:23 UTC, softhack007 commented
Hi guys @arneboe @netmindz,
I'm preparing for a MM release this weekend. Would it be ok for you if we merge DMX changes after the release?

2023-12-15 17:18 UTC, netmindz commented
Yeah that's fine @softhack007

2023-12-30 18:56 UTC, netmindz commented
Are you able to resolve the conflicts @arneboe ?

2024-01-16 09:23 UTC, arneboe commented
I can try to take a look on the weekend but no promises.

2024-01-16 09:36 UTC, netmindz commented
Thanks. It's really just the platformio change that matters, for the html stuff it will just be running the npm task and submitting your change

2024-01-16 19:10 UTC, netmindz commented
Github let me resolve the conflict, but then doesn't give me permission to commit the result of "npm run build" @arneboe

2024-01-17 19:12 UTC, netmindz commented
I've made a few tweaks, if you can merge the the MM dmx_input branch into yours, then I think we are good to then accept this PR

2024-02-10 17:40 UTC, merged

2025-01-23 09:07 UTC, netmindz commented
You might be interested to know @arneboe this has now been merged upstream into WLED-AV